version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    image: gilded-rose
    container_name: gilded-rose-app
    restart: unless-stopped
    volumes:
      - ./:/var/www/html
